# Generated by Django 3.1.3 on 2020-11-23 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_companyname', models.CharField(max_length=100)),
                ('company_username', models.CharField(max_length=50)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('company_description', models.TextField()),
            ],
        ),
    ]
