# Generated by Django 3.1.3 on 2020-11-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testimonial_imgs')),
                ('testimonial', models.CharField(max_length=100)),
                ('founder_name', models.CharField(max_length=50)),
                ('founder_title', models.CharField(max_length=50)),
            ],
        ),
    ]
