# Generated by Django 3.1.3 on 2021-07-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolios',
            name='website_link',
            field=models.URLField(blank=True, default='enter link', max_length=150, null=True),
        ),
    ]
